### ISSUE TITLE
创建应用步骤，一直卡在创建中。查看gitlab已经创建完成。

### ISSUE THREAD

**Issue by zeroingsu** [choerodon/choerodon#11]
Choerodon平台版本: 0.9.0

遇到问题的执行步骤:
创建应用步骤，一直卡在创建中。查看gitlab已经创建完成。

环境信息(如:节点信息):
k8s 1.8.5

报错日志:

17:33:01.220 [PollingServerListUpdater-1] INFO c.n.config.ChainedDynamicProperty - Flipping property: gitlab-service.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
17:33:25.287 [Asgard-saga-consumer-1] WARN io.choerodon.asgard.saga.SagaMonitor - sagaMonitor invoke method error, transaction rollback, msg SagaTaskInstanceDTO{id=11, sagaInstanceId=5, taskCode=‘devopsOperationGitlabProject’, sagaCode=‘devops-create-gitlab-project’, instanceLock=‘null’, status=‘RUNNING’, seq=1, input=’{“userId”:1,“path”:“axe”,“groupId”:3,“type”:“application”,“organizationId”:1}’}, cause
io.choerodon.core.exception.CommonException: error.git.push
at io.choerodon.devops.infra.common.util.GitUtil.push(GitUtil.java:217)
at io.choerodon.devops.app.service.impl.ApplicationServiceImpl.operationApplication(ApplicationServiceImpl.java:300)
at io.choerodon.devops.api.eventhandler.DevopsSagaHandler.createApp(DevopsSagaHandler.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.invoke(SagaMonitor.java:194)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.run(SagaMonitor.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

17:33:28.714 [Asgard-saga-consumer-2] WARN io.choerodon.asgard.saga.SagaMonitor - sagaMonitor invoke method error, transaction rollback, msg SagaTaskInstanceDTO{id=11, sagaInstanceId=5, taskCode=‘devopsOperationGitlabProject’, sagaCode=‘devops-create-gitlab-project’, instanceLock=‘172.20.154.153:8060’, status=‘RUNNING’, seq=1, input=’{“userId”:1,“path”:“axe”,“groupId”:3,“type”:“application”,“organizationId”:1}’}, cause
io.choerodon.core.exception.CommonException: error.git.push
at io.choerodon.devops.infra.common.util.GitUtil.push(GitUtil.java:217)
at io.choerodon.devops.app.service.impl.ApplicationServiceImpl.operationApplication(ApplicationServiceImpl.java:300)
at io.choerodon.devops.api.eventhandler.DevopsSagaHandler.createApp(DevopsSagaHandler.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.invoke(SagaMonitor.java:194)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.run(SagaMonitor.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

17:33:30.845 [AsyncResolver-bootstrap-executor-0] INFO c.n.d.s.r.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
17:34:53.175 [Asgard-saga-consumer-3] WARN io.choerodon.asgard.saga.SagaMonitor - sagaMonitor invoke method error, transaction rollback, msg SagaTaskInstanceDTO{id=12, sagaInstanceId=6, taskCode=‘devopsCreateEnv’, sagaCode=‘devops-create-env’, instanceLock=‘null’, status=‘RUNNING’, seq=1, input=’{“userId”:1,“path”:“dev”,“gitlabProjectId”:null,“groupId”:2,“type”:“ENV”,“organizationId”:null}’}, cause
io.choerodon.core.exception.CommonException: error.projecthook.create
at io.choerodon.devops.infra.persistence.impl.GitlabRepositoryImpl.createWebHook(GitlabRepositoryImpl.java:142)
at io.choerodon.devops.app.service.impl.DevopsEnvironmentServiceImpl.handleCreateEnvSaga(DevopsEnvironmentServiceImpl.java:349)
at io.choerodon.devops.api.eventhandler.DevopsSagaHandler.devopsCreateUser(DevopsSagaHandler.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.invoke(SagaMonitor.java:194)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.run(SagaMonitor.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

17:34:54.321 [Asgard-saga-consumer-4] WARN io.choerodon.asgard.saga.SagaMonitor - sagaMonitor invoke method error, transaction rollback, msg SagaTaskInstanceDTO{id=12, sagaInstanceId=6, taskCode=‘devopsCreateEnv’, sagaCode=‘devops-create-env’, instanceLock=‘172.20.154.153:8060’, status=‘RUNNING’, seq=1, input=’{“userId”:1,“path”:“dev”,“gitlabProjectId”:null,“groupId”:2,“type”:“ENV”,“organizationId”:null}’}, cause
feign.FeignException: status 400 reading GitlabServiceClient#createDeploykey(Integer,String,String,boolean,Integer); content:
{“timestamp”:“2018-09-17 17:34:54”,“status”:400,“error”:“Bad Request”,“exception”:“org.springframework.web.bind.MissingServletRequestParameterException”,“message”:“Required Integer parameter ‘projectId’ is not present”,“path”:"/v1/projects/deploy_key"}
at feign.FeignException.errorStatus(FeignException.java:62)
at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
at com.sun.proxy.$Proxy212.createDeploykey(Unknown Source)
at io.choerodon.devops.infra.persistence.impl.GitlabRepositoryImpl.createDeployKey(GitlabRepositoryImpl.java:159)
at io.choerodon.devops.app.service.impl.DevopsEnvironmentServiceImpl.handleCreateEnvSaga(DevopsEnvironmentServiceImpl.java:336)
at io.choerodon.devops.api.eventhandler.DevopsSagaHandler.devopsCreateUser(DevopsSagaHandler.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.invoke(SagaMonitor.java:194)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.run(SagaMonitor.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

java.lang.IllegalArgumentException: Illegal character in path at index 34: http://gitlab-service/v1/projects/{projectId}/protected_branches?name=master&mergeAccessLevel=40&pushAccessLevel=40&userId=1
	at java.net.URI.create(URI.java:852)
	at org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:56)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy212.createProtectedBranches(Unknown Source)
	at io.choerodon.devops.infra.persistence.impl.GitlabRepositoryImpl.createProtectBranch(GitlabRepositoryImpl.java:119)
	at io.choerodon.devops.app.service.impl.ApplicationServiceImpl.operationApplication(ApplicationServiceImpl.java:302)
	at io.choerodon.devops.api.eventhandler.DevopsSagaHandler.createApp(DevopsSagaHandler.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.invoke(SagaMonitor.java:194)
	at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.run(SagaMonitor.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 34: http://gitlab-service/v1/projects/{projectId}/protected_branches?name=master&mergeAccessLevel=40&pushAccessLevel=40&userId=1
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 17 more

**Comment by ganshanshan** [comment]
你好！我是Choerodon猪齿鱼社区的负责人 甘闪闪，非常感谢你提出的意见，我们会认真对待。Choerodon猪齿鱼产品部署这边确实有很多问题，我们内部也在不断的改进，希望产品部署更加方便；社区中的文档等我们会进一步细化更新。

另外，我们能相互加个微信号码，我的微信是18601777272。
