### ISSUE TITLE
管理后台创建项目，但是gitlab上并没有相应的group和project创建出来

### ISSUE THREAD

**Issue by happyyangyuan** [choerodon/choerodon#18]
### Choerodon version
0.10.0
### Actual results
后台日志报错如下
`
2018-11-14 17:54:39.847 WARN [devops-service,,,] 1 --- [saga-consumer-1] io.choerodon.asgard.saga.SagaMonitor : sagaMonitor invoke method error, transaction rollback, msg SagaTaskInstanceDTO{id=18, sagaInstanceId=8, taskCode='devopsCreateGitLabGroup', sagaCode='iam-create-project', instanceLock='null', status='RUNNING', seq=2, input='{"projectId":2,"projectCode":"cedar-pay","projectName":"松付宝","organizationCode":"operation","organizationName":"运营组织","userName":"yangyuan","userId":2,"roleLabels":["project.deploy.admin","project.owner","project.wiki.admin","project.gitlab.owner"]}'}, cause
java.lang.NullPointerException
at io.choerodon.devops.app.service.impl.GitlabGroupServiceImpl.createGroup(GitlabGroupServiceImpl.java:67)
at io.choerodon.devops.api.eventhandler.SagaHandler.handleGitlabGroupEvent(SagaHandler.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.invoke(SagaMonitor.java:194)
at io.choerodon.asgard.saga.SagaMonitor$InvokeTask.run(SagaMonitor.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
`

我已经检查了devops-service内gitlab的相应配置了，没有发现明显错误。

**Comment by happyyangyuan** [comment]
### 补充说明
harbor是可以联动生成了新项目的，gitlab不行。

**Comment by ganshanshan** [comment]
可否把全局事物中对应事物截图来看看吗？

**Comment by ganshanshan** [comment]
补充：全局事物，在顶部菜单“管理”中

**Comment by happyyangyuan** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/9134975/48476274-937ca700-e839-11e8-8af4-631283a3c7ea.png">

**Comment by happyyangyuan** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/9134975/48476481-2584af80-e83a-11e8-8b31-ea908fcbf186.png">

**Comment by happyyangyuan** [comment]
我是用的外置的gitlab哦，不是使用的猪齿鱼内置的gitlab，是这个原因引起的吗？

harbor我也是使用的外置的。

**Comment by happyyangyuan** [comment]
一般公司都有自己的gitlab等现成的版本控制软件的，你们应该能理解吧，干嘛要再独立搭建一套？

**Comment by crockitwood** [comment]
你好，使用我们暂时只支持猪齿鱼配套的GitLab，如有其它问题以及更加详细的咨询以及交流可以在我们论坛进行提问 http://forum.choerodon.io ☺️

**Comment by happyyangyuan** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/9134975/48480905-ce390c00-e846-11e8-8443-c12a0b5b5eb8.png">

我现在部署了猪齿鱼配套的gitlab了，报错如上图所示

**Comment by happyyangyuan** [comment]
发现可能是因为下面的局限性导致的问题：
我执行`helm install c7n/gitlab-service ... --set env.open.GITLAB_PRIVATETOKEN="GEuRhgb6kG9y3prFosSb" ...`命令，参数GITLAB_PRIVATETOKEN是gitlab的admin用户的token，但是我在choerodon里面用的是新建的自暂时定义的组织管理员，而非默认的admin。


也就是说，我猜测是你们可能是系统这个局限于必须是默认的admin才可以成功新建项目，望优化。

**Comment by zhuzhiyang** [comment]
是用什么用户创建的项目？

**Comment by happyyangyuan** [comment]
用的组织管理员用户创建的项目。
ps. 我们今天又遇到了创建app失败，也是联动创建gitlab proejct失败
